### ISSUE TITLE
Asciinema player 실행 오류

### ISSUE THREAD

**Issue by whiteout1024** [hdltools/vscode-asciinema-player#1]
동작 확인을 위해 cast 파일을 열었지만 asciinema player가 실행되지 않는 현상이 있습니다.
사용자 계정 하위에 있는 .vscode/extensions 폴더에 본 repository를 clone 했으며, 
VSCode extensions에서 "Asciinema Player v0.0.1"이 확인된 상황입니다.
![image](https://user-images.githubusercontent.com/91731727/136410494-5119ce76-1b01-4f5d-91b5-d9899d2501b8.png)

**Comment by congeal** [comment]
지금은 패키지로 묶은 게 아니라서, clone 받고 debugging을 실행해야 동작을 확인해 볼 수 있어요.
게다가 source code가 ts라 transpile 없이 바로 실행도 안 되구요. 그래서 extension directory에 clone 한다고 해서 실행되지는 않아요.
이번 주말에 패키지로 묶어 놓을게요.

**Comment by congeal** [comment]
#2 로 패키지 준비 완료
