### ISSUE TITLE
vsix package 생성/설치 후 cast file을 열었을때 player가 동작하지 않음

### ISSUE THREAD

**Issue by whiteout1024** [hdltools/vscode-asciinema-player#4]
![image](https://user-images.githubusercontent.com/91731727/136975911-189c13fe-60dc-427e-b4ed-73ec3de26809.png)

업데이트된 readme에 따라 vsix 파일을 생성하고 "Extensions: Install from VXIS..." 메뉴를 통해 정상 설치 후 example cast 파일을 열었을때 player가 실행되지 않는 현상이 있습니다.
생선된 vsix 파일은 74.06KB로 확인되며 아래와 같은 node package를 global로 install한 환경에서 package를 생성했습니다.

/usr/local/lib       
├── eslint@8.0.0     
├── fs@0.0.1-security
├── mysql@2.18.1     
├── npm@7.22.0       
├── path@0.12.7      
├── typescript@4.4.3
├── vsce@1.100.1
└── vscode@1.1.37

개발환경 구성에 있어 빠진 부분이 있다면 의견을 부탁드립니다.

**Comment by congeal** [comment]
내가 테스트 했을 때는 잘 됐는데 뭐가 모르겠네요.
내가 만든 패키지는 160kb 정도 되네요.
내가 만든 vsix 패키지를 릴리즈에 올려놨으니, 이걸로 테스트 해보고 결과를 좀 알려주세요:
https://github.com/hdltools/vscode-asciinema-player/releases/tag/0.0.1

**Comment by congeal** [comment]
slack?

**Comment by whiteout1024** [comment]
공유해주신 vsix 파일을 설치한경우 정상적으로 동작함을 확인했으며,
Package build 환경 구성에 문제가 있는 것으로 판단됩니다.
다만, 원인 파악이 쉽지 않네요. :(
![image](https://user-images.githubusercontent.com/91731727/137122661-b4e29659-921d-4910-9e06-3ed0097446d4.png)

**Comment by whiteout1024** [comment]
'npm install' command를 실행하지 않아서 발생한 문제로 확인되었습니다.
필요 package를 설치한 이후에는 233Kb 크기의 vsix 파일이 생성되며 기대되는 동작을 수행합니다.
